### ISSUE TITLE
contract not found

### ISSUE THREAD

**Issue by condorjea** [stephanfowler/nft-surface#1]
Hello,

Im tring to deploy and start but im getting

C:\MyProjects\nft-surface-main\smart-contract>npx hardhat deploy --args ./delpoyment_args_rinkeby.js --network rinkeby
Nothing to compile
Error HH700: Artifact for contract "NFTsurface" not found

const NFTsurface = await ethers.getContractFactory('NFTsurface'); //Where NFTSurface or where can i find contract source for the 
deployment.

Thank You

**Comment by stephanfowler** [comment]
Apologies, only just saw this. The contract is there now, it got dropped from git after a rename. Let me know if you have any other difficulties.
